# Generated by Django 6.0.7 on 2026-07-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
